- name: Install MySQL and related
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-mysql
    - python-mysqldb
    - mysql-server

# Set up MySQL, see http://stackoverflow.com/a/16446163
- name: Update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 172.16.100.1
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: DANGER Bind MySQL to 172.16.100.2:3306 when 'testing' is true
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line='bind-address = 172.16.100.2'
  notify: restart mysql
  when: testing

- name: Add SQL user 'ontoden'
  mysql_user: name=ontoden password={{ mysql_ontoden_password }} priv=ontoden.*:ALL state=present

- name: Upload Ontoden default SQL
  copy: src=ontoden.sql dest=/tmp/ontoden.sql

- name: Create Ontoden SQL database
  mysql_db: name=ontoden state=present
  notify: import ontoden.sql
