- name: Pre-configure triplestore admin password
  debconf: name=virtuoso-opensource question=virtuoso-opensource-6.1/dba-password value={{ virtuoso_dba_password }} vtype=password

- name: Confirm triplestore admin password
  debconf: name=virtuoso-opensource question=virtuoso-opensource-6.1/dba-password-again value={{ virtuoso_dba_password }} vtype=password

- name: Install triplestore
  apt: pkg=virtuoso-opensource state=installed
  notify: restart virtuoso

# To do this manually see http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtTipsAndTricksGuideImportOntology
- name: Upload ontologies.sql import script
  copy: src=ontologies.sql dest=/tmp/ontologies.sql
  notify: import ontologies
