- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=installed
  with_items:
    - apt-transport-https
    - apticron
    - build-essential
    - debian-goodies
    - subversion
    - git
    - htop
    - iftop
    - iotop
    - python-software-properties
    - ruby1.9.3
    - screen
    - sudo
    - update-notifier-common
    - vim
    - emacs
    - zsh

- name: Install unattended upgrades
  apt: pkg=unattended-upgrades state=installed

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

- name: Update sshd config to disallow root logins
  lineinfile: dest=/etc/ssh/sshd_config regexp=^PermitRootLogin line="PermitRootLogin no" state=present
  notify: restart ssh

- include: apache.yml tags=apache
- include: ufw.yml tags=ufw
  when: not testing
