- name: Install ufw
  apt: pkg=ufw state=present

- name: Deny everything and enable UFW
  ufw: state=enabled policy=deny

- name: Set firewall rules for web traffic and SSH
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - http
    - ssh

- name: Check config of ufw
  command: cat /etc/ufw/ufw.conf
  register: ufw_config
  changed_when: False  # never report as "changed"

- name: Disable logging (workaround for known bug in Debian 7)
  ufw: logging=off
  when: "ansible_lsb['codename'] == 'wheezy' and 'LOGLEVEL=off' not in ufw_config.stdout"
